### ISSUE TITLE
can't run client

### ISSUE THREAD

**Issue by ITwrx** [lunchboxav/svelte-rust-boilerplate#2]
hi,
thanks for the repo. I'm interested in svelte + rust backend, so i'm interested to try this out, but i'm not very well versed in the js ecosystem and the client won't builld/run. Maybe you know why?

```
yarn run dev:client
yarn run v1.21.1
$ (cd client && npm run start)
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1600234880080-0.10577401840937228/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @ start /run/media/myuser/myhdd/Documents/rust_programs/svelte-rust-boilerplate/client
> snowpack dev


Error: Cannot find module '@snowpack/app-scripts-svelte'
Require stack:
- /run/media/myuser/myhdd/Documents/rust_programs/svelte-rust-boilerplate/node_modules/snowpack/dist-node/index.js
- /run/media/myuser/myhdd/Documents/rust_programs/svelte-rust-boilerplate/node_modules/snowpack/dist-node/index.bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at loadAndValidateConfig (/run/media/myuser/myhdd/Documents/rust_programs/svelte-rust-boilerplate/node_modules/snowpack/dist-node/index.js:3594:132)
    at cli (/run/media/myuser/myhdd/Documents/rust_programs/svelte-rust-boilerplate/node_modules/snowpack/dist-node/index.js:5825:18)
    at Object.<anonymous> (/run/media/myuser/myhdd/Documents/rust_programs/svelte-rust-boilerplate/node_modules/snowpack/dist-node/index.bin.js:29:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `snowpack dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myuser/.npm/_logs/2020-09-16T05_41_20_764Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ITwrx** [comment]
well i got it running with: 

```
npm i @snowpack/app-scripts-svelte
npm i svelte-compiler
npm i svelte
```
i don't know if that was the best/correct way to do it but....
